server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: utf-8
            enabled: true

spring:
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 2MB

logging:
    level:
        root: DEBUG